export const MIN_MOVEMENT_DISTANCE = 5;
export const MIN_MOVEMENT_DISTANCE_GUIDANCE = 3;

export const HEADING_SMOOTHING_FACTOR = 0.3;

export const MIN_HEADING_CHANGE = 8;

export const CAMERA_FOLLOW_DURATION = 800;
export const CAMERA_FOLLOW_DURATION_GUIDANCE = 500;
export const CAMERA_ORIENTATION_DURATION = 500;

export const GUIDANCE_PITCH = 15;

export const WATCH_INTERVAL_MS = 1000;
export const WATCH_INTERVAL_MS_GUIDANCE = 700;

export const MAX_ACCEPTED_ACCURACY = 50;

export const HEADING_ENABLE_ACCURACY = 15;

export const GUIDANCE_LEG_FIT_DURATION = 1500;
export const GUIDANCE_HOLD_DURATION = 500;

export const GUIDANCE_ARRIVAL_RADIUS = 30;
export const GUIDANCE_TRANSFER_RADIUS = 35;
export const GUIDANCE_DESTINATION_RADIUS = 25;
export const GUIDANCE_APPROACHING_RADIUS = 80;
export const GUIDANCE_AUTO_ADVANCE_MIN_INTERVAL = 3000;
export const GUIDANCE_AUTO_ADVANCE_STABILITY = 2;

export const CAMERA_SAFE_RADIUS_WALK = 12;
export const CAMERA_UPDATE_INTERVAL_WALK = 2000;
export const CAMERA_MIN_HEADING_DELTA_WALK = 15;
export const CAMERA_MIN_SPEED_BEARING_WALK = 1.0;
export const GUIDANCE_ZOOM_WALK = 17;
export const CAMERA_DURATION_WALK = 1000;

export const CAMERA_SAFE_RADIUS_TRANSIT = 40;
export const CAMERA_UPDATE_INTERVAL_TRANSIT = 4000;
export const CAMERA_MIN_HEADING_DELTA_TRANSIT = 30;
export const CAMERA_MIN_SPEED_BEARING_TRANSIT = 3.0;
export const GUIDANCE_ZOOM_TRANSIT = 14;
export const GUIDANCE_ZOOM_TRANSFER = 15.5;
export const CAMERA_DURATION_TRANSIT = 2000;

export const GUIDANCE_DEVIATION_DISTANCE = 200;
export const GUIDANCE_DEVIATION_STABILITY = 6;

export const CAMERA_SAFE_RADIUS_TRANSFER = 20;
export const CAMERA_UPDATE_INTERVAL_TRANSFER = 4000;
export const CAMERA_MIN_HEADING_DELTA_TRANSFER = 45;
export const CAMERA_DURATION_TRANSFER = 1500;
