export const MIN_MOVEMENT_DISTANCE = 5;
export const MIN_MOVEMENT_DISTANCE_GUIDANCE = 3;

export const HEADING_SMOOTHING_FACTOR = 0.3;

export const MIN_HEADING_CHANGE = 8;

export const CAMERA_FOLLOW_DURATION = 800;
export const CAMERA_FOLLOW_DURATION_GUIDANCE = 500;
export const CAMERA_ORIENTATION_DURATION = 500;

export const GUIDANCE_PITCH = 15;

export const WATCH_INTERVAL_MS = 1000;
export const WATCH_INTERVAL_MS_GUIDANCE = 700;

export const MAX_ACCEPTED_ACCURACY = 50;

export const HEADING_ENABLE_ACCURACY = 15;

export const GUIDANCE_LEG_FIT_DURATION = 1500;
